# Generated by Django 4.1.6 on 2023-02-11 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Ter',
            fields=[
                ('uf', models.IntegerField()),
                ('nome_UF', models.CharField(max_length=256)),
                ('regiao_geografica_intermediaria', models.IntegerField()),
                ('nome_regiao_geografica_intermediaria', models.CharField(max_length=256)),
                ('regiao_geografica_imediata', models.IntegerField()),
                ('nome_regiao_geografica_imediata', models.CharField(max_length=256)),
                ('mesorregiao_geografica', models.IntegerField()),
                ('nome_mesorregiao', models.CharField(max_length=256)),
                ('microrregiao_geografica', models.IntegerField()),
                ('nome_microrregiao', models.CharField(max_length=256)),
                ('municipio', models.IntegerField()),
                ('codigo_municipio_completo', models.CharField(max_length=7)),
                ('nome_municipio', models.CharField(max_length=256)),
                ('cod_municipio', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Repasse_FNS',
            fields=[
                ('bloco', models.CharField(max_length=256)),
                ('grupo', models.CharField(max_length=256)),
                ('acao_detalhada', models.CharField(max_length=256)),
                ('competencia_parcela', models.CharField(max_length=256)),
                ('num_ob', models.CharField(max_length=256)),
                ('data_ob', models.CharField(max_length=10)),
                ('banco_ob', models.CharField(max_length=3)),
                ('agencia_ob', models.CharField(max_length=256)),
                ('conta_ob', models.CharField(max_length=256)),
                ('valor_total', models.FloatField()),
                ('desconto', models.FloatField()),
                ('valor_liquido', models.FloatField()),
                ('observacao', models.CharField(max_length=256)),
                ('processo', models.CharField(max_length=256)),
                ('tipo_repasse', models.CharField(max_length=256)),
                ('num_proposta', models.CharField(max_length=256)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.reg_ter')),
            ],
        ),
    ]
